### ISSUE TITLE
No centralized point for managing data

### ISSUE THREAD

**Issue by jerryjohnjacob** [kishore-narendran/AliensOnEarth#1]
If I wanted to add a new property for aliens, say number of eyes, there's no single point where I can just add it and get everything working as expected. I have to make changes in multiple points, including the plugins themselves. This coupling should be broken up.

**Comment by kishore-narendran** [comment]
The parameters for the alien details can now be edited in the alien-details.js file added in the 576bdff2ec6d3c66ee72619629fe35b046b25bc4 commit.

**Comment by jerryjohnjacob** [comment]
I think this issue has not been fully resolved. While the alien attributes can be extended in the alien-parameters.js file, any changes will not be picked up by the plugins (see https://github.com/kishore-narendran/AliensOnEarth/blob/master/generators/generate-text.js#L12 and https://github.com/kishore-narendran/AliensOnEarth/blob/master/generators/generate-pdf.js#L15).

@kishore-narendran Can you please reopen this issue?

**Comment by kishore-narendran** [comment]
Yeah, you are right! On, it.

**Comment by kishore-narendran** [comment]
The parameter changes will be picked up by the plugins, an oversight on my part. 80c399b3d6cd77c77731323a5112266ecef1cd6f fixes it.

**Comment by jerryjohnjacob** [comment]
As an upgrade to this, can you think of a way to make the data flow a little more solid? Right now there is one source (alien-parameters.js) that governs all the attributes, but there is still a disjoint relation between the parameters and the data itself - i.e. if you look at it now, they are two different arrays. Now even though the system is designed in such a way that the attributes and data values themselves would be ordered appropriately in their respective arrays, I think we should not leave such an important part of the system to just chance like that.

It's actually just a simple tweak, but it's a very important change. Let me know if you need more clarity on this.
@kishore-narendran

**Comment by kishore-narendran** [comment]
I do need some more clarity on this. Do you want me to use the attributes as the key to a corresponding value array of the details accepted from the user?

@jerryjohnjacob

**Comment by jerryjohnjacob** [comment]
@kishore-narendran I think you should zoom out a little bit and consider something other than just an array.

**Comment by kishore-narendran** [comment]
I took another approach to this by using, the parameters as a key to an array that holds the details as entered by the user sequentially. Have a look at 1c6f6d0ec0e23b2d802ecec01ba8c8f604644d1a. I don't know if this is what you were talking about. @jerryjohnjacob

**Comment by jerryjohnjacob** [comment]
I saw that. That wasn't exactly what I was referring to. However, the code you wrote indicates you know the syntax to what I have in mind. Consider a different scenario. There are multiple types of aliens. Some have more features than others. In this case, a single data source governing the list of attributes for all aliens wouldn't solve the problem. Some fundamental changes to how the data is managed would have to be made. Can you think of what those would be?

**Comment by kishore-narendran** [comment]
What about having multiple data sources and pointing to them at runtime?

**Comment by jerryjohnjacob** [comment]
I think there's a simpler solution than that.

**Comment by kishore-narendran** [comment]
An array of JSON objects where each element describes the different kind of parameters for the different types of aliens as you suggested. 

But that would require some further prompting before entering the details. Right?

-----Original Message-----

**Comment by jerryjohnjacob** [comment]
Something like that :). How would you implement this?

**Comment by kishore-narendran** [comment]
Okay, I think a good approach would be to make it a JSON array where each object is a list of characteristics and a unique identifier name or tag to accept the details. Which can be later used to distinguish between what needs to be accepted at runtime. 

-----Original Message-----

**Comment by jerryjohnjacob** [comment]
Why not have the individual objects drive what attributes need to be inputted in the first place?

**Comment by kishore-narendran** [comment]
You mean flexibly allow for any attribute to be inputted as per the needs of the user? And not request for all?

-----Original Message-----

**Comment by jerryjohnjacob** [comment]
No, I meant have the object govern what the user will input.

**Comment by kishore-narendran** [comment]
Do you mean in this fashion?

```
var alienDetails = [
    {set one of parameters},
    {set two of parameters}, ....
]
```

-----Original Message-----

**Comment by jerryjohnjacob** [comment]
The same functionality can be achieved in a much cleaner way. The multiple alien parameters feature was just a hint as to how you should approach the problem.

**Comment by kishore-narendran** [comment]
What if I worked out the parameters in the following manner? I have been a little puzzled.

```
var alienDetails = {
"firstSetOfDetail": {
"parameters": [],
"data": []
}
"secondSetOfDetail": {
"parameters": [],
"data": []
}
}
```

**Comment by jerryjohnjacob** [comment]
This is essentially the gist of what I'm referring to. But what better approach can you use to arrive at such a setup? By better, I refer to a cleaner approach rather than just JSON data objects.

**Comment by kishore-narendran** [comment]
Why not use a database. Like MongoDB? 

-----Original Message-----

**Comment by jerryjohnjacob** [comment]
I was merely hinting at a class for aliens. This class would have a mechanism to indicate what attributes it wants. New alien types could potentially inherit from a basic type of alien with shared attributes.
