### ISSUE TITLE
Too much dependency on the prompts for the application to work

### ISSUE THREAD

**Issue by jerryjohnjacob** [kishore-narendran/AliensOnEarth#2]
If you look at the line https://github.com/kishore-narendran/AliensOnEarth/blob/master/aliens.js#L50 or https://github.com/kishore-narendran/AliensOnEarth/blob/master/aliens.js#L61, the prompts are governing what the attributes are going to be called.

If there is an error (such as a simple typo in the name of an attribute), the entire application would stop working since there is too much coupling between how the user is prompted to enter data and the actual alien attributes. This needs to change to such a way that the prompts are driven by a data source and not the other way around.

**Comment by kishore-narendran** [comment]
The prompts are now being driven by data source first introduced as a variable in b3f382433c3e451296f3a08c4eef8508df7c14c5 and then shifted to a separate file called alien-parameters.js in 576bdff2ec6d3c66ee72619629fe35b046b25bc4
