### ISSUE TITLE
Further segregation of code required

### ISSUE THREAD

**Issue by jerryjohnjacob** [kishore-narendran/AliensOnEarth#3]
The aliens.js file is driving every aspect of the application, for instance, deciding alien attributes, prompting for the values for these attributes, deciding which format to use and even importing the required file and invoking the export. The code should be a little more modularized.

**Comment by kishore-narendran** [comment]
I find further segregation of code in [aliens.js](https://github.com/kishore-narendran/AliensOnEarth/blob/master/aliens.js) unnecessary. 

What do you think?

**Comment by jerryjohnjacob** [comment]
With the latest  changes, perhaps segregation may no longer be required. However, it feels a little odd that the first prompt is initiated by a method whose name indicates that it will check whether to continue. It feels like a hack to reuse the prompting code. I think you should refactor the code around this.

**Comment by kishore-narendran** [comment]
Fixed in 22b980eb934e93f78f31610049463512500d617c
