### ISSUE TITLE
Remove code duplication

### ISSUE THREAD

**Issue by jerryjohnjacob** [kishore-narendran/AliensOnEarth#4]
If you observe lines https://github.com/kishore-narendran/AliensOnEarth/blob/master/aliens.js#L50 and https://github.com/kishore-narendran/AliensOnEarth/blob/master/aliens.js#L61, they are the exact same lines of code. This is a bigger problem in this context because to do something as simple as add a new attribute during prompt, the change has to be done in two places.

This is similar to the issue mentioned here - https://github.com/kishore-narendran/AliensOnEarth/issues/2 - but the effect of the duplication is different here.

**Comment by kishore-narendran** [comment]
Code duplication has been removed in 576bdff2ec6d3c66ee72619629fe35b046b25bc4. Please suggest if there is a better way to do this.
