### ISSUE TITLE
Addition of a new plugin (generator) requires changes in the code for it to work

### ISSUE THREAD

**Issue by jerryjohnjacob** [kishore-narendran/AliensOnEarth#5]
To add a new plugin, I see two steps would be required. One is to add it to the generators folder and the other is to add an entry in the command line arguments file (https://github.com/kishore-narendran/AliensOnEarth/blob/master/command-line-arguments.js).

The expectation we have is that by simply introducing the appropriate file for the plugin in the correct location will cause the system to automatically support the new plugin. No changes should be required anywhere in the codebase other than this.

**Comment by kishore-narendran** [comment]
What if that change was not in the source code, but was on a config file of some sorts?
Or is it better to auto generate the command line arguments?

**Comment by kishore-narendran** [comment]
An alternative is to add only the generator file to the generators folder and auto generate command line arguments, as implemented in ec5953c8a09c1a522cb0a6c87e5e3ca2c3e60bca. However, this does directly conflict this [issue](https://github.com/kishore-narendran/AliensOnEarth/issues/6)

**Comment by jerryjohnjacob** [comment]
Enforcing a format for the file names of the plugins solves this issue. But as you have already identified, issue #6 is still unsolved. Can you figure out a way to achieve both objectives? (Hint: you may have to change your approach slightly on the plugin front)
