### ISSUE TITLE
Too much dependency on generator code file names

### ISSUE THREAD

**Issue by jerryjohnjacob** [kishore-narendran/AliensOnEarth#6]
The application depends heavily on the names of the plugin files (See https://github.com/kishore-narendran/AliensOnEarth/blob/master/aliens.js#L29). The system should ideally not have any dependency with any such aspects that are not controllable.

**Comment by kishore-narendran** [comment]
One way that it can be controlled is to define a naming convention for the generator files, forcing the CL tool to accept and use only those generator files of the format `generator-<FORMAT NAME>.js`

So we either adopt this approach, or addition of plugins should depend on the addition of the files and the editing of source code for command line arguments.

**Comment by kishore-narendran** [comment]
I have now written a CL tool for adding new generators. This will take care of naming conventions for the generator files and will hence abstract away that from plugin developers and users and can hence be controlled. Done in 5886d2ef46e6661116501af109e739e064bfc67c. 

The CL tool can be used given the updated instructions in the [README.md](https://github.com/kishore-narendran/AliensOnEarth/blob/master/README.md)

**Comment by jerryjohnjacob** [comment]
Looks good :)
