### ISSUE TITLE
add-generator.js could be more modularized

### ISSUE THREAD

**Issue by jerryjohnjacob** [kishore-narendran/AliensOnEarth#8]
The delegation of the addition of new plugins to a different unit is great. But the add-generator.js code could use a bit more of modularization. It may seem trivial, but the fundamentals of good-quality code include readability and easy maintenance. From that perspective, this new file can be improved.

**Comment by kishore-narendran** [comment]
d8aed857ef56ff676267e2d93378bd463935d12f improves modularity?
Can this be improved further?

**Comment by jerryjohnjacob** [comment]
Yes, this looks much better.
